# Numpy

In [3]:
import numpy as np
import random

In [11]:
#np.arange()
# create a matrix of size 10,3 with random integers ranging -5 to 5

x = np.random.randint(-5, 5,size=(10,3))
print(x)
print(x.shape)
print(x.T)

[[-1  3  1]
 [-5 -5 -2]
 [ 1  0 -4]
 [ 0  1 -2]
 [ 2  4  1]
 [-2 -5 -2]
 [ 1 -4  3]
 [ 0 -4  1]
 [-5  2 -4]
 [-5  0  4]]
(10, 3)
[[-1 -5  1  0  2 -2  1  0 -5 -5]
 [ 3 -5  0  1  4 -5 -4 -4  2  0]
 [ 1 -2 -4 -2  1 -2  3  1 -4  4]]


In [14]:
w = np.random.random(size=(1,3))
print(w)

b=0

[[0.89095316 0.30671721 0.31846622]]


In [17]:
# n = w*x.T +b

n = np.dot(w,x.T) + b
print(n,"\n",n.shape)

[[ 0.3476647  -6.62528434 -0.38291172 -0.33021523  3.32724141 -3.95242484
   0.61948297 -0.90840264 -5.11519628 -3.18090094]] 
 (1, 10)


In [30]:
def ppn(x):
    out = []
    for i in x[0]:
        if(i>=0):
            out.append(1)
        else:
            out.append(-1)
    return out
    

In [32]:
print(ppn(n))

[1, -1, -1, -1, 1, -1, 1, -1, -1, -1]


In [34]:
#another method to do above task

out1 = np.where(n[0]>0, 1, -1)
print(out1)

[ 1 -1 -1 -1  1 -1  1 -1 -1 -1]


In [36]:
#find number of 1 and -1

c = 0
for i in out1:
    if(i==1):
        c+=1
        print()
        
print("1's",c)
print("-1's",len(out1)-c)

1's 3
-1's 7


In [37]:
#another way 
n1 = (out1==1).sum()    #out1==1 is comparison which gives 1 or 0 as output which can be summed
n2 = (out1==-1).sum()
print("number of 1 = ", n1)
print("number of -1 = ", n2)

number of 1 =  3
number of -1 =  7


In [41]:
#find index of 1 and -1

c1_index = np.where(out1==1)
print(c1_index)
print(c1_index[0])

c2_index = np.where(out1==-1)
print(c2_index)
print(c2_index[0])

(array([0, 4, 6], dtype=int64),)
[0 4 6]
(array([1, 2, 3, 5, 7, 8, 9], dtype=int64),)
[1 2 3 5 7 8 9]


In [46]:
print(out1)
o2 = np.reshape(out1, (2, 5))   #only take given elements i.e, new one has to be multilple 
print(o2)

o2 = np.resize(out1, (2, 15))   #can take any shape and create matrix by copying
print(o2)

[ 1 -1 -1 -1  1 -1  1 -1 -1 -1]
[[ 1 -1 -1 -1  1]
 [-1  1 -1 -1 -1]]
[[ 1 -1 -1 -1  1 -1  1 -1 -1 -1  1 -1 -1 -1  1]
 [-1  1 -1 -1 -1  1 -1 -1 -1  1 -1  1 -1 -1 -1]]


## Activation Functions

to limit output between a certain range

1 - (no limt) Linear / Identity -> f(x) = x

2 - (0,1) threshhold / binarystep -> f(x) = 1 if x>=0 and -1 if x<0

3 - [0,1] logsigmoid -> f(x) = 1/(1+e^(-x))

4 - (-1,1) tanh -> f(x) = (2/(1+e^(-2x))) -1

5 - (-pi/2,pi/2) qrctan -> f(x) = tan^(-1)(x)

6 - (0,x) ReLu -> f(x) = 0 for x<0 and x for x>=0

7 - (0.01,x) Leaky ReLu -> f(X) = 0.01*x for x<0 and x for x>0

In [ ]:
#Plot all activation functions in a single figure using subplots